version: "3.8"

services:

  redis:
    image: redis
    container_name: redis
    platform: linux/amd64
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - default

  postgres:
    image: postgres
    container_name: postgres
    platform: linux/amd64
    ports:
      - "5422:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: form_cv_dummy
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-U", "user"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    networks:
      - default

  mysql:
    image: mysql:5.7
    container_name: mysql
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$password"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  mongo_data:
  postgres_data:
